
package MAS.WebService.DirectDistributionSystem;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "BookingException", targetNamespace = "http://WebService.MAS/")
public class BookingException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private BookingException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public BookingException_Exception(String message, BookingException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public BookingException_Exception(String message, BookingException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: MAS.WebService.DirectDistributionSystem.BookingException
     */
    public BookingException getFaultInfo() {
        return faultInfo;
    }

}
