
package MAS.WebService.DirectDistributionSystem;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DirectDistributionSystem", targetNamespace = "http://WebService.MAS/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DirectDistributionSystem {


    /**
     * 
     * @param date
     * @param passengerCount
     * @param origin
     * @param travelDuration
     * @param destination
     * @param travelClass
     * @return
     *     returns java.util.List<MAS.WebService.DirectDistributionSystem.WsFlightResultArray>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchAvailableFlights", targetNamespace = "http://WebService.MAS/", className = "MAS.WebService.DirectDistributionSystem.SearchAvailableFlights")
    @ResponseWrapper(localName = "searchAvailableFlightsResponse", targetNamespace = "http://WebService.MAS/", className = "MAS.WebService.DirectDistributionSystem.SearchAvailableFlightsResponse")
    @Action(input = "http://WebService.MAS/DirectDistributionSystem/searchAvailableFlightsRequest", output = "http://WebService.MAS/DirectDistributionSystem/searchAvailableFlightsResponse")
    public List<WsFlightResultArray> searchAvailableFlights(
        @WebParam(name = "origin", targetNamespace = "")
        String origin,
        @WebParam(name = "destination", targetNamespace = "")
        String destination,
        @WebParam(name = "date", targetNamespace = "")
        XMLGregorianCalendar date,
        @WebParam(name = "passengerCount", targetNamespace = "")
        int passengerCount,
        @WebParam(name = "travelClass", targetNamespace = "")
        int travelClass,
        @WebParam(name = "travelDuration", targetNamespace = "")
        int travelDuration);

}
