
package MAS.WebService.FFPAlliance;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "FFPAlliance", targetNamespace = "http://WebService.MAS/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FFPAlliance {


    /**
     * 
     * @param ffpNumber
     * @param miles
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "awardMiles", targetNamespace = "http://WebService.MAS/", className = "MAS.WebService.FFPAlliance.AwardMiles")
    @ResponseWrapper(localName = "awardMilesResponse", targetNamespace = "http://WebService.MAS/", className = "MAS.WebService.FFPAlliance.AwardMilesResponse")
    @Action(input = "http://WebService.MAS/FFPAlliance/awardMilesRequest", output = "http://WebService.MAS/FFPAlliance/awardMilesResponse")
    public boolean awardMiles(
        @WebParam(name = "ffpNumber", targetNamespace = "")
        long ffpNumber,
        @WebParam(name = "miles", targetNamespace = "")
        int miles);

}
