
package MAS.WebService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PartnerMilesService", targetNamespace = "http://WebService.MAS/", wsdlLocation = "http://localhost:8080/PartnerWeb_war_exploded/services/PartnerMiles?wsdl")
public class PartnerMilesService
    extends Service
{

    private final static URL PARTNERMILESSERVICE_WSDL_LOCATION;
    private final static WebServiceException PARTNERMILESSERVICE_EXCEPTION;
    private final static QName PARTNERMILESSERVICE_QNAME = new QName("http://WebService.MAS/", "PartnerMilesService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/PartnerWeb_war_exploded/services/PartnerMiles?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PARTNERMILESSERVICE_WSDL_LOCATION = url;
        PARTNERMILESSERVICE_EXCEPTION = e;
    }

    public PartnerMilesService() {
        super(__getWsdlLocation(), PARTNERMILESSERVICE_QNAME);
    }

    public PartnerMilesService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PARTNERMILESSERVICE_QNAME, features);
    }

    public PartnerMilesService(URL wsdlLocation) {
        super(wsdlLocation, PARTNERMILESSERVICE_QNAME);
    }

    public PartnerMilesService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PARTNERMILESSERVICE_QNAME, features);
    }

    public PartnerMilesService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PartnerMilesService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PartnerMiles
     */
    @WebEndpoint(name = "PartnerMilesPort")
    public PartnerMiles getPartnerMilesPort() {
        return super.getPort(new QName("http://WebService.MAS/", "PartnerMilesPort"), PartnerMiles.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PartnerMiles
     */
    @WebEndpoint(name = "PartnerMilesPort")
    public PartnerMiles getPartnerMilesPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://WebService.MAS/", "PartnerMilesPort"), PartnerMiles.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PARTNERMILESSERVICE_EXCEPTION!= null) {
            throw PARTNERMILESSERVICE_EXCEPTION;
        }
        return PARTNERMILESSERVICE_WSDL_LOCATION;
    }

}
