
package MAS.WebService;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DirectDistributionSystem", targetNamespace = "http://WebService.MAS/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DirectDistributionSystem {


    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg5
     * @param arg4
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<MAS.WebService.WsSearchResult>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchAvailableFlights", targetNamespace = "http://WebService.MAS/", className = "MAS.WebService.SearchAvailableFlights")
    @ResponseWrapper(localName = "searchAvailableFlightsResponse", targetNamespace = "http://WebService.MAS/", className = "MAS.WebService.SearchAvailableFlightsResponse")
    @Action(input = "http://WebService.MAS/DirectDistributionSystem/searchAvailableFlightsRequest", output = "http://WebService.MAS/DirectDistributionSystem/searchAvailableFlightsResponse")
    public List<WsSearchResult> searchAvailableFlights(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        XMLGregorianCalendar arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        int arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        int arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        int arg5);

}
